# Generated by Django 5.2.10 on 2026-02-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0003_merge_20260221_1307"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contractevent",
            name="ingest_cont_contrac_idx_timestamp",
        ),
        migrations.RemoveIndex(
            model_name="contractevent",
            name="ingest_cont_contrac_idx_event_type",
        ),
        migrations.RemoveIndex(
            model_name="contractevent",
            name="ingest_cont_timestamp_idx",
        ),
    ]
